name: Build LaTeX Documents

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate Simulation Images"]
    types: [completed]

jobs:
  build_latex:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Compile LaTeX Documents
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: latex
          root_file: |
            article_apophatic_dynamics.tex
            article_apophatic_optimization.tex
            article_forces_and_constants.tex
            article_math_riemann.tex
            article_triade_intractabilities.tex
            article_yang_mills_mass_gap.tex
            article_meth_space.tex
            article_meth_riemann.tex
            article_meth_bsd.tex
            article_meth_hodgepoincare.tex
          args: "-pdf -bibtex -file-line-error -interaction=nonstopmode"

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Manuscripts
          path: latex/*.pdf
