name: Build "Apophatic Optimization" LaTeX Document

on:
  workflow_dispatch:

jobs:
  run-sim:
    uses: nicht-organization/nicht-physics/.github/workflows/generate_images.yml@main
    secrets: inherit
  build-latex:
    uses: nicht-organization/nicht-theory/.github/workflows/compile_latex_base.yml@main
    with:
      root-file: article_apophatic_optimization.tex