name: Build "Apophatic Dynamics" LaTeX Document

on:
  workflow_dispatch:

jobs:
  build-latex:
    uses: nicht-organization/nicht-theory/.github/workflows/compile_latex_base.yml@main
    with:
      root-file: article_apophatic_dynamics.tex